export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

// export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
// export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
// export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const ORDER_ALL_REQUEST = "ORDER_ALL_REQUEST";
export const ORDER_ALL_SUCCESS = "ORDER_ALL_SUCCESS";
export const ORDER_ALL_FAIL = "ORDER_ALL_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

export const ORDER_CONFIRMED_REQUEST = "ORDER_CONFIRMED_REQUEST";
export const ORDER_CONFIRMED_SUCCESS = "ORDER_CONFIRMED_SUCCESS";
export const ORDER_CONFIRMED_FAIL = "ORDER_CONFIRMED_FAIL";
export const ORDER_CONFIRMED_RESET = "ORDER_CONFIRMED_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";
